CREATE TABLE users
(
    id           CHAR(36) PRIMARY KEY,
    phone_number VARCHAR(15) NOT NULL UNIQUE,
    name         VARCHAR(100),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
